version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - pip install -r requirements.txt
  post_build:
    commands:
      - python manage.py runserver  &
artifacts:
  files:
    - '**/*'
  
